export { default as WorldLogo } from './wordIcon.svg';
export { default as MapIcon } from './mapIcon.svg';
export { default as Pailot } from './pailot.svg';
export { default as Scan } from './scan.svg';
export { default as LeftArrow } from './leftArrow.svg';
export { default as LogOut } from './logOut.svg';
export { default as ProfileIcon } from './profileIcon.svg';
export { default as AddressIcon } from './addressIcon.svg';
export { default as BackgroundIcon } from './backgroundIcon.svg';
export { default as EditIcon } from './editIcon.svg';
export { default as NameIcon } from './nameIcon.svg';
export { default as PhoneIcon } from './phoneIcon.svg';
export { default as PictureIcon } from './pictureIcon.svg';
export { default as PiIcon } from './piIcon.svg';
export { default as PlusIcon } from './plusIcon.svg';
export { default as ProfileAvatarIcon } from './profileAvatarIcon.svg';
export { default as SettingIcon } from './settingIcon.svg';
export { default as UserIcon } from './userIcon.svg';
export { default as WalletIcon } from './walletIcon.svg';
export { default as CameraIcon } from './cameraIcon.svg';
export { default as ClearIcon } from './clearIcon.svg';
export { default as CheckIcon } from './checkIcon.svg';
export { default as filter } from './filter.svg';
export { default as nigerianFlag } from './nigerianFlag.svg';
export { default as pailotSettings } from './pailotSettings.svg';
export { RiFingerprintFill, RiCalendarTodoLine, RiLogoutCircleRLine } from 'react-icons/ri';
export { GrFormClose, GrStatusWarning } from 'react-icons/gr';
export { BiError, BiErrorAlt } from 'react-icons/bi';
export { BsPentagon, BsCheckLg, BsInfoLg } from 'react-icons/bs';
export { AiOutlineShoppingCart, AiOutlineWallet, AiOutlineArrowLeft } from 'react-icons/ai';
export { MdClose } from 'react-icons/md';
export { default as WorldIcon } from './worldIcon.svg';
export { IoMdArrowRoundBack } from 'react-icons/io';
